# Generated by Django 5.1.3 on 2024-11-08 04:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('Numero_de_factura', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)])),
                ('fecha_de_emision', models.DateField(auto_now_add=True)),
                ('Cedula', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Ventas.cliente')),
            ],
        ),
    ]
